// TypesFromSerializers CacheKey 4879ce64a3c4793bf653d7334c95e185
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MessageTemplatesFormData {
      id?: string
      slug?: string
      body: string
      medium: string
      mediums: string[]
      name: string
      subject?: string
    }
  }
}
