// TypesFromSerializers CacheKey a9eb5ba57df31287e4625a0a6111eea6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MessageTemplatesIndex {
      id: string
      body: string
      medium: string
      name: string
      slug: string
      subject?: string
    }
  }
}
