// TypesFromSerializers CacheKey 8a40ad0825cf5b9b2438a4a10f4ec143
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MessageTemplatesPersisted {
      id: string
      body: string
      medium: string
      name: string
      slug: string
      subject?: string
    }
  }
}
