# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `boolean_timestamp` gem.
# Please instead update this file by running `bin/tapioca gem boolean_timestamp`.

# source://boolean_timestamp//lib/boolean_timestamp/version.rb#1
module BooleanTimestamp
  mixes_in_class_methods ::BooleanTimestamp::ClassMethods

  class << self
    # @private
    #
    # source://boolean_timestamp//lib/boolean_timestamp.rb#6
    def included(base); end
  end
end

# source://boolean_timestamp//lib/boolean_timestamp.rb#10
module BooleanTimestamp::ClassMethods
  # source://boolean_timestamp//lib/boolean_timestamp.rb#11
  def boolean_timestamp(method_name, strict: T.unsafe(nil)); end

  private

  # source://boolean_timestamp//lib/boolean_timestamp.rb#49
  def define_boolean_timestamp_accessors(method_name, column_name, strict:); end

  # source://boolean_timestamp//lib/boolean_timestamp.rb#73
  def define_boolean_timestamp_loose_reader(method_name, column_name); end

  # source://boolean_timestamp//lib/boolean_timestamp.rb#44
  def define_boolean_timestamp_loose_scopes(method_name, fully_qualified_column_name); end

  # source://boolean_timestamp//lib/boolean_timestamp.rb#22
  def define_boolean_timestamp_scopes(method_name, fully_qualified_column_name, strict:); end

  # source://boolean_timestamp//lib/boolean_timestamp.rb#67
  def define_boolean_timestamp_strict_reader(method_name, column_name); end

  # source://boolean_timestamp//lib/boolean_timestamp.rb#30
  def define_boolean_timestamp_strict_scopes(method_name, fully_qualified_column_name); end
end

# source://boolean_timestamp//lib/boolean_timestamp/version.rb#2
BooleanTimestamp::VERSION = T.let(T.unsafe(nil), String)
