// TypesFromSerializers CacheKey 9cdf686ae8c829df253fb5a4983c4fe9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PresentationsSettings from '../../Presentations/Settings'

declare global {
  namespace Schema {
    interface ThemesPresentationsSummary {
      id: string
      active: boolean
      name: string
      settings: PresentationsSettings
      slides_count: number
      slug: string
      theme_id: string
    }
  }
}
