// TypesFromSerializers CacheKey 21f53b29d90686634cee88d09c7be70d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesPresentationsSummary {
      id: string
      active: boolean
      name: string
      slides_count: number
      slug: string
      theme_id: string
    }
  }
}
