// TypesFromSerializers CacheKey 4e88172eea3c7d288847a87f99be32ed
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistributionsEdit {
      id: string
      created_at: string | Date
      name: string
      template: boolean
      type?: number
      updated_at: string | Date
    }
  }
}
