// TypesFromSerializers CacheKey adb8d825d9f1797ecbad1f80be054113
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistributionsEdit {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
