// TypesFromSerializers CacheKey e6d80a5e2f37f9e4f7fcfa0a8863a750
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistributionsFormData {
      id?: string
      name: string
      template: boolean
      type?: number
    }
  }
}
