// TypesFromSerializers CacheKey 96b167c2304266d5edd79217f0b195af
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistributionsIndex {
      id: string
      created_at: string | Date
      name: string
      template: boolean
      type?: number
      updated_at: string | Date
    }
  }
}
