// TypesFromSerializers CacheKey ba1cf515d84bca59e086c3622997fd0d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistributionsPersisted {
      id: string
      created_at: string | Date
      name: string
      template: boolean
      type?: number
      updated_at: string | Date
    }
  }
}
