// TypesFromSerializers CacheKey 7ce8d4b52dc3dc8efb42d1e65e1cd57f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistributionsPersisted {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
