// TypesFromSerializers CacheKey 6d531c599e29a6585691202c207bd794
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistributionsPersisted {
      id: string
      created_at: string | Date
      name: string
      template: boolean
      type?: number
      updated_at: string | Date
    }
  }
}
