// TypesFromSerializers CacheKey 9a46596160d9f8351ac38f9ffb19fbf3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistributionsShow {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
