// TypesFromSerializers CacheKey a9e0a9c58084b486005dcf0d2bcabe82
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PresentationsPersisted from '../../Presentations/Persisted'

declare global {
  namespace Schema {
    interface PresentationDistributionsShow {
      id: string
      created_at: string | Date
      name: string
      presentations: PresentationsPersisted[]
      template: boolean
      type?: number
      updated_at: string | Date
    }
  }
}
