// TypesFromSerializers CacheKey c12636c5e0d74ecc60b2250c699d88a0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesEdit {
      id: string
      created_at: string | Date
      updated_at: string | Date
    }
  }
}
