// TypesFromSerializers CacheKey 00eb9c2839976a1c50fd3e2852943553
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesEdit {
      id: unknown
      created_at: unknown
      name: unknown
      type: unknown
      updated_at: unknown
    }
  }
}
