// TypesFromSerializers CacheKey 4744114c5a0ea1b624aa09f110c9d137
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesFormData {
      id?: unknown
      name: unknown
      type: unknown
    }
  }
}
