// TypesFromSerializers CacheKey a6d596d49fcbfa5edf4f98276383b30a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesFormData {
      id?: string
    }
  }
}
