// TypesFromSerializers CacheKey 2228352a0e1772bc31c6195ca54d4b1b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesFormData {
      id?: unknown
      name: unknown
      type: unknown
    }
  }
}
