// TypesFromSerializers CacheKey d9671c4eb12feb253ac7c30852bbe9d9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesIndex {
      id: unknown
      created_at: unknown
      name: unknown
      type: unknown
      updated_at: unknown
    }
  }
}
