// TypesFromSerializers CacheKey 4e133559a506682ea5b746d1d977c614
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesPersisted {
      id: string
      created_at: string | Date
      name?: string
      type?: number
      updated_at: string | Date
    }
  }
}
