// TypesFromSerializers CacheKey 937a60abef2755471b67a68a8af96430
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesPersisted {
      id: unknown
      created_at: unknown
      name: unknown
      type: unknown
      updated_at: unknown
    }
  }
}
