// TypesFromSerializers CacheKey 5c3db24439056cb6e5873d74508f80c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeveragesPersisted {
      id: string
      created_at: string | Date
      updated_at: string | Date
    }
  }
}
