// TypesFromSerializers CacheKey a41cc7b2d69e7ad9d2975c05f1d83ac9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Slide from '../../Slide'

declare global {
  namespace Schema {
    interface SlidesEdit {
      id: string
      created_at: string | Date
      data: Slide
      slug?: string
      title?: string
      updated_at: string | Date
    }
  }
}
