// TypesFromSerializers CacheKey c9354cf789f876b14b97d049ae84b7b5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlideData from '../../SlideData'

declare global {
  namespace Schema {
    interface SlidesEdit {
      id: string
      data: SlideData
      slug: string
      title?: string
    }
  }
}
