// TypesFromSerializers CacheKey 54b1ddf3c5daa50856c9bf9fb2a4c094
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlideData from '../../SlideData'

declare global {
  namespace Schema {
    interface SlidesEdit {
      id: string
      data: SlideData
      slug: string
      thumbnail_url?: string
      title?: string
    }
  }
}
