// TypesFromSerializers CacheKey 0d5ac77fc3464eafed796870e4595322
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlideData from '../../SlideData'

declare global {
  namespace Schema {
    interface SlidesFormData {
      id?: string
      slug?: string
      data: SlideData
      title?: string
    }
  }
}
