// TypesFromSerializers CacheKey c9708173b062a996647db20d54b30cd9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SlidesFormData {
      id?: string
      slug?: string
      data?: Record<string, string>
      title?: string
    }
  }
}
