// TypesFromSerializers CacheKey ffea6141acf5f9bad1ec90b739626e81
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlideData from '../../SlideData'

declare global {
  namespace Schema {
    interface SlidesIndex {
      id: string
      data: SlideData
      slug: string
      title?: string
    }
  }
}
