// TypesFromSerializers CacheKey 3641a4b623bb642978390edf2a781761
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlideData from '../../SlideData'

declare global {
  namespace Schema {
    interface SlidesIndex {
      id: string
      data: SlideData
      slug: string
      thumbnail_url?: string
      title?: string
    }
  }
}
