// TypesFromSerializers CacheKey 02b4d1a3ed8fc31817b32dcc7fcc5b66
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SlidesIndex {
      id: string
      created_at: string | Date
      data?: Record<string, string>
      slug?: string
      title?: string
      updated_at: string | Date
    }
  }
}
