// TypesFromSerializers CacheKey a24fb9ba51b3609a2de7b5779455f59f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlideData from '../../SlideData'

declare global {
  namespace Schema {
    interface SlidesPresentation {
      id: string
      data: SlideData
      slug: string
      title?: string
    }
  }
}
