// TypesFromSerializers CacheKey 305d9c4b209158282644b203d0ef510c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SlidesShow {
      id: string
      created_at: string | Date
      data?: Record<string, string>
      slug?: string
      title?: string
      updated_at: string | Date
    }
  }
}
