// TypesFromSerializers CacheKey f7e2661d252e26a71dd6525250535315
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlideData from '../../SlideData'

declare global {
  namespace Schema {
    interface SlidesShow {
      id: string
      data: SlideData
      slug: string
      thumbnail_url?: string
      title?: string
    }
  }
}
