// TypesFromSerializers CacheKey 214fb4b2000cbb8ff2a3274a2fdcba81
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../../Money'
import type CirclesPersisted from '../../Circles/Persisted'

declare global {
  namespace Schema {
    interface ThemesOrgsShow {
      id: string
      ask: Money
      circle: CirclesPersisted
      description?: string
      name: string
      slug: string
    }
  }
}
