// TypesFromSerializers CacheKey 4426d4430336049d88a0b7578fcfd0a3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../../Money'
import type CirclesPersisted from '../../Circles/Persisted'

declare global {
  namespace Schema {
    interface ThemesOrgsShow {
      id: string
      ask: Money
      circle: CirclesPersisted
      created_at: string | Date
      description?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
