// TypesFromSerializers CacheKey bfe0cc78b36470c7f719096f67804eb9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../../Money'
import type CirclesPersisted from '../../Circles/Persisted'

declare global {
  namespace Schema {
    interface ThemesOrgsShow {
      id: string
      ask: Money
      circle: CirclesPersisted
      circle_id: string
      created_at: string | Date
      description?: string
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
