// TypesFromSerializers CacheKey 3d36dca94f12ded2d1ca403206e7b916
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Activity {
      id: number
      createdAt: string | Date
      key?: string
      ownerId?: number
      ownerType?: string
      parameters?: string
      recipientId?: number
      recipientType?: string
      trackableId?: number
      trackableType?: string
      updatedAt: string | Date
    }
  }
}
