// TypesFromSerializers CacheKey a202afd02cb05c72abfd6c369dcf9999
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Address {
      id?: string
      address?: string
      address_2?: string
      category_id: unknown
      city?: string
      contact_id: string
      country?: string
      name: unknown
      notes: unknown
      postal?: string
      region?: string
    }
  }
}
