// TypesFromSerializers CacheKey d0cae090a168fc33924f2af9a8e2db4f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Category {
      id?: string
      slug?: string
      categorizable_type: string
      description?: string
      name: string
    }
  }
}
