// TypesFromSerializers CacheKey a5302ab5ce3abec6f21bdc3b7aab1c70
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Circle {
      id?: string
      slug?: string
      name: string
    }
  }
}
