// TypesFromSerializers CacheKey f4dbbe61d7f3c53d9655096190b1a9c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Circle {
      id?: number
      slug?: string
      name: string
    }
  }
}
