// TypesFromSerializers CacheKey a6c234d1ad6f93d277fa0d9bf687a04f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Circle {
      id?: string
      slug?: string
      name: string
    }
  }
}
