// TypesFromSerializers CacheKey 11d38d2681b6e3628e57fd97f5a61cae
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Email {
      id?: string
      category_id: unknown
      contact_id?: string
      email?: string
      name: unknown
      notes: unknown
    }
  }
}
