// TypesFromSerializers CacheKey 6923fd50c9b1b2e08ed5868e7f690d44
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from './Category'

declare global {
  namespace Schema {
    interface Email {
      id?: string
      category: Category
      category_id: string
      contact_id: string
      email?: string
      name: unknown
      notes: unknown
    }
  }
}
