// TypesFromSerializers CacheKey 6fdc5eb856f71584f1038fb6f7e07a47
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Group {
      id?: string
      slug?: string
      circle_id: unknown
      name: string
    }
  }
}
