// TypesFromSerializers CacheKey 21177b4f0ec345c0f698e7836cff8eca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from './InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface InteractionConfigTemplate {
      id?: string
      slug?: string
      config: Record<string, string>
      interaction_ui_template?: InteractionUiTemplatesPersisted
      name: string
    }
  }
}
