// TypesFromSerializers CacheKey ca0492e5766d2bca993c284dcf854a80
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface InteractionUiTemplate {
      id?: string
      slug?: string
      name: string
    }
  }
}
