// TypesFromSerializers CacheKey d5ee39055672a21aa63cd34bfc0c2f4e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from './InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface InteractionConfigTemplate {
      id?: string
      slug?: string
      config: Record<string, string>
      interaction_ui_template?: InteractionUiTemplatesPersisted
      member_ui: Record<string, string>
      name: string
    }
  }
}
