// TypesFromSerializers CacheKey 48be255045eb133ba3327643898e8a4e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface InteractionConfigTemplate {
      id?: string
      slug?: string
      config: Record<string, string>
      name: string
    }
  }
}
