// TypesFromSerializers CacheKey 49ba95d899c67a9352746322687382e4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../Money'

declare global {
  namespace Schema {
    interface Membership {
      id?: string
      slug?: string
      active: boolean
      funds: Money
      name: string
      number?: string
    }
  }
}
