// TypesFromSerializers CacheKey cf471c1c862d84ba3f289767fd6cd0c7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Members {
      id?: number
      firstName?: string
      lastName?: string
      number?: string
    }
  }
}
