// TypesFromSerializers CacheKey c0718a127995155e537654234a39676f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Membership {
      id?: string
    }
  }
}
