// TypesFromSerializers CacheKey 701016d05e03436bc30917bf2a7fc5a2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Member {
      id?: number
      created_at: string | Date
      first_name?: string
      last_name?: string
      number?: string
      updated_at: string | Date
    }
  }
}
