// TypesFromSerializers CacheKey 97cdfbb41617bc8d863cfd0052758581
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../Money'

declare global {
  namespace Schema {
    interface Membership {
      id?: string
      slug?: string
      active: boolean
      funds: Money
      name: string
      number?: string
    }
  }
}
