// TypesFromSerializers CacheKey 2f4a9c52c645b0c427ceed27ab3f9497
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Member {
      id?: number
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      number?: string
    }
  }
}
