// TypesFromSerializers CacheKey 60ac04fd70387cab954a10d2665c0ff1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Member {
      id?: string
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      number?: string
    }
  }
}
