// TypesFromSerializers CacheKey bbafaec5838076343e119ee7cd14fc40
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MessageTemplate {
      id?: string
      slug?: string
      body: string
      medium: string
      name: string
      subject?: string
    }
  }
}
