// TypesFromSerializers CacheKey 08933df19d7760dc7f664b62f35c1add
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Org {
      id?: number
      created_at: string | Date
      description?: string
      name?: string
      slug?: string
      updated_at: string | Date
    }
  }
}
