// TypesFromSerializers CacheKey 7ee8c81c9dcb6a31c42cdcd326ab4ea2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Org {
      id?: string
      slug?: string
      description?: string
      name?: string
    }
  }
}
