// TypesFromSerializers CacheKey 6359ad4219c3b88829c15e9b4355e9fd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Org {
      id?: string
      slug?: string
      circle_id: string
      description?: string
      name?: string
    }
  }
}
