// TypesFromSerializers CacheKey 90979d04e834fc65c39927fbf6baf8d0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Person {
      id?: string
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: unknown
    }
  }
}
