// TypesFromSerializers CacheKey 7f2a1f587213acabcc185a2c42e08864
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Phone {
      id?: string
      extension: unknown
      name: unknown
      number?: string
    }
  }
}
