// TypesFromSerializers CacheKey 8379429a5928caebc0144f410722b295
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from './Category'

declare global {
  namespace Schema {
    interface Phone {
      id?: string
      category: Category
      category_id: string
      contact_id: string
      extension: unknown
      name: unknown
      number?: string
    }
  }
}
