// TypesFromSerializers CacheKey 9c9b4ce2cf9e2740ea4d4102c07091fe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlide {
      id?: string
      slug?: string
      content?: string
      name?: string
      order?: number
      presentation_id?: string
      presentation_template_id?: string
    }
  }
}
