// TypesFromSerializers CacheKey 3c7fd25c5319a7cde65116561bfffbcd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplate {
      id?: number
      name?: string
    }
  }
}
