// TypesFromSerializers CacheKey fdbfdacdce6950ac279d42f180e0261e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Presentation {
      id?: string
      active: boolean
      name: string
      theme_id: string
    }
  }
}
