// TypesFromSerializers CacheKey 0b64d1a93ad49aa83464c9a0bdf5a4e6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeverage {
      id?: string
    }
  }
}
