// TypesFromSerializers CacheKey 36585b0e3a9c7f3355bbf2f33497f0a9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeverage {
      id?: unknown
      name: unknown
      type: unknown
    }
  }
}
