// TypesFromSerializers CacheKey 4a8e527f7f425cd7de2a5b32742d0d30
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Presentation {
      id?: string
      active: boolean
      name?: string
      theme_id: string
    }
  }
}
