// TypesFromSerializers CacheKey 7f893e92af1671affae02eb33331172e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Presentation {
      id?: string
      active: boolean
      name: string
      slides: Record<string, string>
      theme_id: string
    }
  }
}
