// TypesFromSerializers CacheKey 6f939f329a4246eef21b1a978481f972
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVote {
      id?: unknown
    }
  }
}
