// TypesFromSerializers CacheKey f00179c9d2932e9f86430fe45b45b043
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVote {
      id?: unknown
    }
  }
}
