// TypesFromSerializers CacheKey 2d1b8c1579ca66a96704bcce1439e1b6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVote {
      id?: string
    }
  }
}
