// TypesFromSerializers CacheKey 3d6c399a72e4f7c9ac6b0e0cc31735bd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationLeverage {
      id?: string
      name?: string
      type?: number
    }
  }
}
