// TypesFromSerializers CacheKey e7c98a0d16785d719c20e840d3664ed9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplate {
      id?: string
      name?: string
    }
  }
}
