// TypesFromSerializers CacheKey 289911cf709ce95ec1c4b7228165e44a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Activity } from './Activity'
import type { User } from './User'

declare global {
  namespace Schema {
    interface Role {
      id?: unknown
      activities: Activity[]
      createdAt: unknown
      name: unknown
      resourceId: unknown
      resourceType: unknown
      updatedAt: unknown
      users: User[]
    }
  }
}
