// TypesFromSerializers CacheKey 968381cf1f57affebd9ddc789af10776
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Slide from '../Slide'

declare global {
  namespace Schema {
    interface Slide {
      id?: string
      slug?: string
      data: Slide
      title?: string
    }
  }
}
