// TypesFromSerializers CacheKey 80beecbb491a08e5440df1f201746582
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlideData from '../SlideData'

declare global {
  namespace Schema {
    interface Slide {
      id?: string
      slug?: string
      data: SlideData
      thumbnail_url?: string
      title?: string
    }
  }
}
