// TypesFromSerializers CacheKey b6594c57d935ab59d33e03a6c9ba70d7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Slide {
      id?: string
      slug?: string
      data?: Record<string, string>
      title?: string
    }
  }
}
