// TypesFromSerializers CacheKey 843f5e764d3bdb9d9f1ed3e60b956216
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Theme {
      id: number
      slug?: string
      published: unknown
      status: number
      title?: string
    }
  }
}
