// TypesFromSerializers CacheKey 9bb07eda083c952168928d4e13259b28
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Theme {
      id?: string
      slug?: string
      circle_id: unknown
      name?: string
      published_at?: string | Date
      status: "draft" | "current" | "past" | "future"
    }
  }
}
