// TypesFromSerializers CacheKey 078d5aedaf2988eb683cd8437b91441a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Theme {
      id?: string
      slug?: string
      name?: string
      published_at?: string | Date
      status: "draft" | "current" | "past" | "future"
    }
  }
}
