// TypesFromSerializers CacheKey d71cb8b638dee206b6221fd2e8d0b260
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Activity } from './Activity'

declare global {
  namespace Schema {
    interface User {
      id?: number
      active: unknown
      activities: Activity[]
      confirmationSentAt: unknown
      confirmedAt: unknown
      createdAt: string | Date
      currentSignInAt: unknown
      currentSignInIp: unknown
      email: string
      failedAttempts: unknown
      lastSignInAt: unknown
      lastSignInIp: unknown
      lockedAt: unknown
      rememberCreatedAt?: string | Date
      resetPasswordSentAt?: string | Date
      signInCount: unknown
      unconfirmedEmail: unknown
      updatedAt: string | Date
    }
  }
}
