// TypesFromSerializers CacheKey f462de5ecd34f77ebf98b969986ea0e3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface User {
      id?: number
      created_at: string | Date
      email: string
      remember_created_at?: string | Date
      updated_at: string | Date
    }
  }
}
