// TypesFromSerializers CacheKey 4c1670a6a89005310c6fbc110190261f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplatesEdit {
      id: string
      circle_id: string
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
