// TypesFromSerializers CacheKey cca5848ac3198e0a87afb6406da60c18
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesShare from '../Circles/Share'

declare global {
  namespace Schema {
    interface PresentationTemplatesEdit {
      id: string
      circle: CirclesShare
      circle_id: string
      created_at: string | Date
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
