// TypesFromSerializers CacheKey 382676694e5e6469f4b803faccabb340
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplatesEdit {
      id: number
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
