// TypesFromSerializers CacheKey 27064fc20cbfb1efe068bf91f21b3883
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplatesFormData {
      id?: string
      circle_id: string
      name?: string
    }
  }
}
