// TypesFromSerializers CacheKey 512ee81c7f6e249ca12a8c2fa20444da
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplatesFormData {
      id?: number
      name?: string
    }
  }
}
