// TypesFromSerializers CacheKey f250ddcc882615b833c14512e8ec9fca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplatesFormData {
      id?: string
      name?: string
    }
  }
}
