// TypesFromSerializers CacheKey a2bf78753abdf509cdde5f310e27dabf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesShare from '../Circles/Share'

declare global {
  namespace Schema {
    interface PresentationTemplatesIndex {
      id: string
      circle: CirclesShare
      circle_id: string
      created_at: string | Date
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
