// TypesFromSerializers CacheKey b103b8c7bb67f19fc25b3c4644f0a058
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface PresentationTemplatesIndex {
      id: string
      circle: CirclesPersisted
      circle_id: string
      created_at: string | Date
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
