// TypesFromSerializers CacheKey 3363b5f163aef4dd2b234c34453f8906
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface PresentationTemplatesIndex {
      id: unknown
      circle: CirclesPersisted
      created_at: unknown
      name: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
