// TypesFromSerializers CacheKey a8a4e05a523dbaeca22072b309f40d04
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplatesShow {
      id: string
      circle_id: string
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
