// TypesFromSerializers CacheKey 1050e39b463ea25c91d53a3df66175c2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationTemplatesShow {
      id: string
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
