// TypesFromSerializers CacheKey 954b4a5f112869002ec813d10734e01f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesEdit {
      id: string
      name: string
      slug: string
    }
  }
}
