// TypesFromSerializers CacheKey 5d29d007a71be9aa681013c0c0d99c33
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesEdit {
      id: number
      name?: string
      slug: string
    }
  }
}
