// TypesFromSerializers CacheKey 874127a558ff3b4c8b7d6eeda3ebd4be
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesEdit {
      id: string
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
