// TypesFromSerializers CacheKey 9fe2c92d6d3e3222224b3fec3acf0512
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesFont {
      id?: string
      family: string
      filename: string
      signed_id: string
      url: string
    }
  }
}
