// TypesFromSerializers CacheKey a7c4c8184171ceddfb06f597c52c76a4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesFormData {
      id?: string
      slug?: string
      name: string
    }
  }
}
