// TypesFromSerializers CacheKey 10de594eb1e2e7532ccf3702cf485632
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ThemesIndex from '../Themes/Index'

declare global {
  namespace Schema {
    interface CirclesIndex {
      id: string
      created_at: string | Date
      name: string
      slug: string
      themes: ThemesIndex[]
      updated_at: string | Date
    }
  }
}
