// TypesFromSerializers CacheKey e2e50944511d9fc43d6426bf88fcb5f8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ThemesPersisted from '../Themes/Persisted'

declare global {
  namespace Schema {
    interface CirclesIndex {
      id: string
      memberships_count: number
      name: string
      slug: string
      themes: ThemesPersisted[]
      themes_count: number
    }
  }
}
