// TypesFromSerializers CacheKey 573d3f274c6766e6af15091020146e11
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ThemesPersisted from '../Themes/Persisted'

declare global {
  namespace Schema {
    interface CirclesIndex {
      id: string
      name: string
      slug: string
      themes: ThemesPersisted[]
    }
  }
}
