// TypesFromSerializers CacheKey e8226be5bb10ec46fd870f24a1efa17e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesInertiaShare {
      id: string
      name: string
      slug: string
    }
  }
}
