// TypesFromSerializers CacheKey 261193be078779c4ca359319ffdca9ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesInertiaShare {
      id: string
      name: string
      slug: string
    }
  }
}
