// TypesFromSerializers CacheKey 7a169f18d8f404868d733e7dd50b533f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesSettings from './Settings'
import type ThemesInertiaShare from '../Themes/InertiaShare'

declare global {
  namespace Schema {
    interface CirclesInertiaShare {
      id: string
      name: string
      settings: CirclesSettings
      slug: string
      themes: ThemesInertiaShare[]
    }
  }
}
