// TypesFromSerializers CacheKey 7991706d43d7d194eed8656341d6bdd3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type MembershipsPersisted from '../Memberships/Persisted'
import type OrgsPersisted from '../Orgs/Persisted'
import type ThemesPersisted from '../Themes/Persisted'

declare global {
  namespace Schema {
    interface CirclesMock {
      id: string
      finalist_count: number
      memberships: MembershipsPersisted[]
      name: string
      orgs: OrgsPersisted[]
      slug: string
      themes: ThemesPersisted[]
    }
  }
}
