// TypesFromSerializers CacheKey a8f7cc35dcf6d04b3c7b95125879a09d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesOptions {
      id: string
      name: string
      slug: string
    }
  }
}
