// TypesFromSerializers CacheKey ba9f0f4fe69e909cd20eb914cf05c337
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesPersisted {
      id: string
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
