// TypesFromSerializers CacheKey dcaec0f8542d80d1e42cbc1c9655ac7b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesPersisted {
      id: string
      name: string
      slug: string
    }
  }
}
