// TypesFromSerializers CacheKey 5323493c2c0a9963300c6395e847f8f5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesPersisted {
      id: string
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
