// TypesFromSerializers CacheKey a00f9ea96c3d643c01325727ffc1584d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesShare {
      id: string
      name: string
      slug: string
    }
  }
}
