// TypesFromSerializers CacheKey 143f703fc989c07878f19f23f36e99cc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesShow {
      id: number
      created_at: string | Date
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
