// TypesFromSerializers CacheKey 3528b5822c7ddd2db820b177200fef00
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type MembershipsPersisted from '../Memberships/Persisted'
import type ThemesPersisted from '../Themes/Persisted'

declare global {
  namespace Schema {
    interface CirclesShow {
      id: string
      memberships: MembershipsPersisted[]
      name: string
      slug: string
      themes: ThemesPersisted[]
    }
  }
}
