// TypesFromSerializers CacheKey a8b38596e8a6eb0c8d1099d37f4b9def
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesShow {
      id: number
      name?: string
      slug: string
    }
  }
}
