// TypesFromSerializers CacheKey 3c826defee34de98bebc97c062314034
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersEdit {
      id: string
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: unknown
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
