// TypesFromSerializers CacheKey 7e30bcb052d712b0f072daa41152547a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersEdit {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
