// TypesFromSerializers CacheKey 426ed85797da8cab288f5733c5a32408
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersEdit {
      id: number
      first_name?: string
      last_name?: string
      number?: string
    }
  }
}
