// TypesFromSerializers CacheKey d8bec53f5b27a023991daee686fcd2e5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersFormData {
      id?: string
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      number?: string
    }
  }
}
