// TypesFromSerializers CacheKey 6a59c844e17e626134f676826867ddbb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersFormData {
      id?: number
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      number?: string
    }
  }
}
