// TypesFromSerializers CacheKey 72c2493408b6743c1ba0d8c98ec5a3fc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersFormData {
      id?: number
      first_name?: string
      last_name?: string
      number?: string
    }
  }
}
