// TypesFromSerializers CacheKey 4cb339e1f36b061c531afc6e33548733
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersIndex {
      id: string
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: unknown
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
