// TypesFromSerializers CacheKey 4f7acd80cac852ea1a0407b473abfcf1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersIndex {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      number?: string
      updated_at: string | Date
    }
  }
}
