// TypesFromSerializers CacheKey 0718c5326ec84e9919b5b07cc911e6e8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersPersisted {
      id: string
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
