// TypesFromSerializers CacheKey 0dc78223b0c4e13c9c522d51ffdd694e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersShallow {
      id: string
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: unknown
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
