// TypesFromSerializers CacheKey cb61bab28857b6cf65008434a6e6256f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersShallow {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      number?: string
      updated_at: string | Date
    }
  }
}
