// TypesFromSerializers CacheKey 638b9bc437ee4a122f2de3c2ff4f0b1c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersShow {
      id: string
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: unknown
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
