// TypesFromSerializers CacheKey 15b8402f0e4dfccc90aeb2c9a1af2d0a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesOptions from '../Circles/Options'

declare global {
  namespace Schema {
    interface MembersShow {
      id: number
      circle: CirclesOptions[]
      created_at: string | Date
      first_name?: string
      last_name?: string
      number?: string
      updated_at: string | Date
    }
  }
}
