// TypesFromSerializers CacheKey e722dd835e7e9f131146d5374a359641
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersShow {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
