// TypesFromSerializers CacheKey 38a3b45e6e5d6f269f1f5a490122850b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IntegrationsPersisted from '../../Integrations/Persisted'
import type PresentationInteractionsPersisted from '../Interactions/Persisted'
import type MessageTemplatesPersisted from '../../MessageTemplates/Persisted'

declare global {
  namespace Schema {
    interface PresentationMessagesEdit {
      id: string
      body: string
      delivery_results: Record<string, {
    recipient?: string | null
    status?: string
    code?: string
    error_message?: string
    skip_reason?: string
    provider_message_id?: string
  }>
      integration_id?: string
      integrations: IntegrationsPersisted[]
      interactions: PresentationInteractionsPersisted[]
      medium: string
      mediums: string[]
      message_template_id?: string
      message_templates: MessageTemplatesPersisted[]
      name: string
      skip_interaction_id?: string
      slug: string
      status: string
      subject?: string
    }
  }
}
