// TypesFromSerializers CacheKey 54796c7d6e814f95045374de17921d10
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IntegrationsPersisted from '../../Integrations/Persisted'
import type MessageTemplatesPersisted from '../../MessageTemplates/Persisted'
import type PresentationInteractionsPersisted from '../Interactions/Persisted'

declare global {
  namespace Schema {
    interface PresentationMessagesIndex {
      id: string
      body: string
      delivery_results: Record<string, {
    recipient?: string | null
    status?: string
    code?: string
    error_message?: string
    skip_reason?: string
    provider_message_id?: string
  }>
      integration?: IntegrationsPersisted
      integration_id?: string
      medium: string
      message_template?: MessageTemplatesPersisted
      message_template_id?: string
      name: string
      skip_interaction?: PresentationInteractionsPersisted
      skip_interaction_id?: string
      slug: string
      status: string
      subject?: string
    }
  }
}
