// TypesFromSerializers CacheKey 2242839f95258724a6c79903a347139d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesEdit {
      id: unknown
      created_at: unknown
      name: unknown
      type: unknown
      updated_at: unknown
    }
  }
}
