// TypesFromSerializers CacheKey e4c0b78333cb6e7dc47f37f78598560d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesEdit {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      template: boolean
      updated_at: string | Date
    }
  }
}
