// TypesFromSerializers CacheKey a7523817e486f89e1b08e0e9f57136e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesFormData {
      id?: string
      data: Record<string, string>
      name: string
      template: boolean
    }
  }
}
