// TypesFromSerializers CacheKey ad2d0edffcc09f89b151d1372edcc58b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesFormData {
      id?: unknown
      name: unknown
      type: unknown
    }
  }
}
