// TypesFromSerializers CacheKey 8763831f060182e03322ed34d7028fa3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesFormData {
      id?: string
      data: Record<string, string>
      name: string
      template: boolean
    }
  }
}
