// TypesFromSerializers CacheKey 0ac248733bad714d54bad012c56c92ef
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesIndex {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      template: boolean
      updated_at: string | Date
    }
  }
}
