// TypesFromSerializers CacheKey 8894464e47657b1c88eaa21e7749623d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesPersisted {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      template: boolean
      updated_at: string | Date
    }
  }
}
