// TypesFromSerializers CacheKey c27663908b990afa3b2a96b09581b59f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PresentationsPersisted from '../../Presentations/Persisted'

declare global {
  namespace Schema {
    interface PresentationVotesShow {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      presentations: PresentationsPersisted[]
      template: boolean
      updated_at: string | Date
    }
  }
}
