// TypesFromSerializers CacheKey 1c91f654df111a20145b83c45d7b03a0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesShow {
      id: unknown
      created_at: unknown
      name: unknown
      type: unknown
      updated_at: unknown
    }
  }
}
