// TypesFromSerializers CacheKey bfbec6956fe95dce3075496f2470a8ca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../../Money'

declare global {
  namespace Schema {
    interface PresentationsActiveMember {
      id: string
      email: string
      finalist_interaction_membership_id: string
      finalist_interaction_slug: string
      finalist_votes: number
      funds: Money
      name: string
      number: string
      presentation_funds: Money
      slug: string
    }
  }
}
