// TypesFromSerializers CacheKey eed390347ce074e75ac1bb5adf4aff98
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesOptions from '../Circles/Options'

declare global {
  namespace Schema {
    interface ThemesDashboard {
      id: string
      circle: CirclesOptions
      description?: string
      heading?: string
      name: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
    }
  }
}
