// TypesFromSerializers CacheKey 148dd648e97385a1e237a18d1cb96a32
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesOptions from '../Circles/Options'

declare global {
  namespace Schema {
    interface ThemesDashboard {
      id: string
      circle: CirclesOptions
      name: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
    }
  }
}
