// TypesFromSerializers CacheKey 414b8df02033d529647234717b07a5a4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesEdit {
      id: string
      created_at: string | Date
      name: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
      updated_at: string | Date
    }
  }
}
