// TypesFromSerializers CacheKey b852b67f308a6acfeae66db2ceb7b7a8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesEdit {
      id: string
      created_at: string | Date
      name?: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
      updated_at: string | Date
    }
  }
}
