// TypesFromSerializers CacheKey dc9f37b44f9fe32b7ac390ad899cca8a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesOptions from '../Circles/Options'

declare global {
  namespace Schema {
    interface ThemesEdit {
      id: string
      circle: CirclesOptions
      name: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
    }
  }
}
