// TypesFromSerializers CacheKey 9a01f1b0623e5d9731a38030c67e227b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesFormData {
      id?: number
      quarter?: string
      question?: string
      title?: string
    }
  }
}
