// TypesFromSerializers CacheKey 230cdd779aa47828618a8800ad73f732
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesFormData {
      id?: string
      slug?: string
      description?: string
      heading?: string
      name: string
      published_at?: string | Date
      status: "draft" | "current" | "past" | "future"
    }
  }
}
