// TypesFromSerializers CacheKey f61f1852cec34d284f3b4f9a6d26668e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesFormData {
      id?: string
      slug?: string
      circle_id: string
      name?: string
      published_at?: string | Date
      status: number
    }
  }
}
