// TypesFromSerializers CacheKey d5ebb0bd0c8bfafe58b32634ba8150c5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesIndex {
      id: string
      created_at: string | Date
      name?: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
      updated_at: string | Date
    }
  }
}
