// TypesFromSerializers CacheKey 6692963833de476e4c8161452e52a07c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesOptions from '../Circles/Options'

declare global {
  namespace Schema {
    interface ThemesIndex {
      id: string
      circle: CirclesOptions
      description?: string
      heading?: string
      name: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
    }
  }
}
