// TypesFromSerializers CacheKey 885c54a5a474dc1fc8891744516a624d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesIndex {
      id: string
      name: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
    }
  }
}
