// TypesFromSerializers CacheKey 6239323e1dbfbba64106466b86559a80
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesInertiaShare {
      id: string
      name?: string
      slug: string
    }
  }
}
