// TypesFromSerializers CacheKey 400d948e9de493e4b800dd65c00458af
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesInertiaShare {
      id: string
      name: string
      slug: string
    }
  }
}
