// TypesFromSerializers CacheKey 12ea29ab9dc694316ee2e2dd27d7aab5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesInertiaShare {
      id: string
      name?: string
      slug: string
    }
  }
}
