// TypesFromSerializers CacheKey dc6968caf24f038cfda8d46e80c41d4d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesPersisted {
      id: string
      created_at: string | Date
      name: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
      updated_at: string | Date
    }
  }
}
