// TypesFromSerializers CacheKey 997b2b0576a5f3e1aea128f7d73253ae
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesPersisted {
      id: string
      created_at: string | Date
      name?: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
      updated_at: string | Date
    }
  }
}
