// TypesFromSerializers CacheKey e7605c6fb00da5fcaa5e35201e4e89bb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesPersisted {
      id: string
      circle_id: string
      created_at: string | Date
      name?: string
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
      updated_at: string | Date
    }
  }
}
