// TypesFromSerializers CacheKey 803e48aabb6ffa0578cd62e66fe098d6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesShallow {
      id: string
      circle_id: string
      created_at: string | Date
      name?: string
      published_at?: string | Date
      slug: string
      status: number
      updated_at: string | Date
    }
  }
}
