// TypesFromSerializers CacheKey 363f7448636f7a7574eaa13207459168
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesShow {
      id: number
      circle_id: number
      created_at: string | Date
      published_at?: string | Date
      slug: string
      status: number
      title?: string
      updated_at: string | Date
    }
  }
}
