// TypesFromSerializers CacheKey 39618481ef8577399ceac02ee2918d00
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'
import type ThemesOrgsShow from './Orgs/Show'

declare global {
  namespace Schema {
    interface ThemesShow {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      orgs: ThemesOrgsShow[]
      published_at?: string | Date
      slug: string
      status: "draft" | "current" | "past" | "future"
      updated_at: string | Date
    }
  }
}
