// TypesFromSerializers CacheKey 76b159f4c2d0175791783393f5cdb5e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesShare from '../Circles/Share'

declare global {
  namespace Schema {
    interface ThemesShow {
      id: number
      circle: CirclesShare
      created_at: string | Date
      published: unknown
      slug: string
      status: number
      title?: string
      updated_at: string | Date
    }
  }
}
