// TypesFromSerializers CacheKey 7f00938fe39245653731eab70d43a14e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteractionsActiveInteraction {
      id: string
      accepting_responses: boolean
      config: Record<string, string>
      context: unknown
      interaction_ui_template: InteractionUiTemplatesPersisted
      member_ui: Record<string, string>
      name: string
      results: Record<string, string>
      slug: string
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
