// TypesFromSerializers CacheKey b33b7e1245b044064475b425bd8c4fc9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteractionsActiveInteraction {
      id: string
      accepting_responses: boolean
      config: Record<string, string>
      context: unknown
      interaction_ui_template: InteractionUiTemplatesPersisted
      name: string
      results: Record<string, string>
      slug: string
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
