// TypesFromSerializers CacheKey 57f82aa49b10a8400b2cb3a5f9e5d805
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationInteractionsControls {
      id: string
      accepting_responses: boolean
      name: string
      slug: string
    }
  }
}
