// TypesFromSerializers CacheKey 3beddcd2269619196b03234538707139
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionConfigTemplatesPersisted from '../../InteractionConfigTemplates/Persisted'
import type InteractionUiTemplatesPersisted from '../../InteractionUiTemplates/Persisted'
import type SlidesPersisted from '../../Slides/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteractionsFormData {
      id?: string
      accepting_responses: boolean
      config: Record<string, string>
      field_types: string[]
      interaction_config_templates: InteractionConfigTemplatesPersisted[]
      interaction_ui_template: InteractionUiTemplatesPersisted
      interaction_ui_templates: InteractionUiTemplatesPersisted[]
      metrics: string[]
      name: string
      reducers: string[]
      results: Record<string, string>
      slides: SlidesPersisted[]
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
