// TypesFromSerializers CacheKey e788d8e3ba86cedaf963026b10bff09e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationInteractionsIndex {
      id: string
      accepting_responses: boolean
      config: Record<string, string>
      name: string
      results: Record<string, string>
      slug: string
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
