// TypesFromSerializers CacheKey 6ea7418258d187f82e6809380f1c7492
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteractionsPersisted {
      id: string
      accepting_responses: boolean
      config: Record<string, string>
      interaction_ui_template: InteractionUiTemplatesPersisted
      member_ui: Record<string, string>
      name: string
      results: Record<string, string>
      slug: string
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
