// TypesFromSerializers CacheKey 5c46a74be040287acbe19469d9b2f30e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteractionsPersisted {
      id: string
      accepting_responses: boolean
      config: Record<string, string>
      interaction_ui_template: InteractionUiTemplatesPersisted
      name: string
      results: Record<string, string>
      slug: string
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
