require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/leverages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Leverage. As you add validations to Leverage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Leverage.create! valid_attributes
      get leverages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      leverage = Leverage.create! valid_attributes
      get leverage_url(leverage)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_leverage_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      leverage = Leverage.create! valid_attributes
      get edit_leverage_url(leverage)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Leverage" do
        expect {
          post leverages_url, params: { leverage: valid_attributes }
        }.to change(Leverage, :count).by(1)
      end

      it "redirects to the created leverage" do
        post leverages_url, params: { leverage: valid_attributes }
        expect(response).to redirect_to(leverage_url(Leverage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Leverage" do
        expect {
          post leverages_url, params: { leverage: invalid_attributes }
        }.to change(Leverage, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post leverages_url, params: { leverage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested leverage" do
        leverage = Leverage.create! valid_attributes
        patch leverage_url(leverage), params: { leverage: new_attributes }
        leverage.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the leverage" do
        leverage = Leverage.create! valid_attributes
        patch leverage_url(leverage), params: { leverage: new_attributes }
        leverage.reload
        expect(response).to redirect_to(leverage_url(leverage))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        leverage = Leverage.create! valid_attributes
        patch leverage_url(leverage), params: { leverage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested leverage" do
      leverage = Leverage.create! valid_attributes
      expect {
        delete leverage_url(leverage)
      }.to change(Leverage, :count).by(-1)
    end

    it "redirects to the leverages list" do
      leverage = Leverage.create! valid_attributes
      delete leverage_url(leverage)
      expect(response).to redirect_to(leverages_url)
    end
  end
end
