require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/presentation_votes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PresentationVote. As you add validations to PresentationVote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PresentationVote.create! valid_attributes
      get presentation_votes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      presentation_vote = PresentationVote.create! valid_attributes
      get presentation_vote_url(presentation_vote)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_presentation_vote_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      presentation_vote = PresentationVote.create! valid_attributes
      get edit_presentation_vote_url(presentation_vote)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PresentationVote" do
        expect {
          post presentation_votes_url, params: { presentation_vote: valid_attributes }
        }.to change(PresentationVote, :count).by(1)
      end

      it "redirects to the created presentation_vote" do
        post presentation_votes_url, params: { presentation_vote: valid_attributes }
        expect(response).to redirect_to(presentation_vote_url(PresentationVote.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PresentationVote" do
        expect {
          post presentation_votes_url, params: { presentation_vote: invalid_attributes }
        }.to change(PresentationVote, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post presentation_votes_url, params: { presentation_vote: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested presentation_vote" do
        presentation_vote = PresentationVote.create! valid_attributes
        patch presentation_vote_url(presentation_vote), params: { presentation_vote: new_attributes }
        presentation_vote.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the presentation_vote" do
        presentation_vote = PresentationVote.create! valid_attributes
        patch presentation_vote_url(presentation_vote), params: { presentation_vote: new_attributes }
        presentation_vote.reload
        expect(response).to redirect_to(presentation_vote_url(presentation_vote))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        presentation_vote = PresentationVote.create! valid_attributes
        patch presentation_vote_url(presentation_vote), params: { presentation_vote: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested presentation_vote" do
      presentation_vote = PresentationVote.create! valid_attributes
      expect {
        delete presentation_vote_url(presentation_vote)
      }.to change(PresentationVote, :count).by(-1)
    end

    it "redirects to the presentation_votes list" do
      presentation_vote = PresentationVote.create! valid_attributes
      delete presentation_vote_url(presentation_vote)
      expect(response).to redirect_to(presentation_votes_url)
    end
  end
end
