require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/template_slides", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TemplateSlide. As you add validations to TemplateSlide, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TemplateSlide.create! valid_attributes
      get template_slides_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      template_slide = TemplateSlide.create! valid_attributes
      get template_slide_url(template_slide)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_template_slide_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      template_slide = TemplateSlide.create! valid_attributes
      get edit_template_slide_url(template_slide)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TemplateSlide" do
        expect {
          post template_slides_url, params: { template_slide: valid_attributes }
        }.to change(TemplateSlide, :count).by(1)
      end

      it "redirects to the created template_slide" do
        post template_slides_url, params: { template_slide: valid_attributes }
        expect(response).to redirect_to(template_slide_url(TemplateSlide.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TemplateSlide" do
        expect {
          post template_slides_url, params: { template_slide: invalid_attributes }
        }.to change(TemplateSlide, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post template_slides_url, params: { template_slide: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested template_slide" do
        template_slide = TemplateSlide.create! valid_attributes
        patch template_slide_url(template_slide), params: { template_slide: new_attributes }
        template_slide.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the template_slide" do
        template_slide = TemplateSlide.create! valid_attributes
        patch template_slide_url(template_slide), params: { template_slide: new_attributes }
        template_slide.reload
        expect(response).to redirect_to(template_slide_url(template_slide))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        template_slide = TemplateSlide.create! valid_attributes
        patch template_slide_url(template_slide), params: { template_slide: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested template_slide" do
      template_slide = TemplateSlide.create! valid_attributes
      expect {
        delete template_slide_url(template_slide)
      }.to change(TemplateSlide, :count).by(-1)
    end

    it "redirects to the template_slides list" do
      template_slide = TemplateSlide.create! valid_attributes
      delete template_slide_url(template_slide)
      expect(response).to redirect_to(template_slides_url)
    end
  end
end
