// TypesFromSerializers CacheKey d9ba7e3a4554d2c303bf095a9cc5f6f4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsEdit {
      id: string
      data: Record<string, string>
      name: string
      slug: string
      template: boolean
    }
  }
}
