// TypesFromSerializers CacheKey 07664680ea02f838cfb1cc4b87203262
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsFormData {
      id?: string
      data: Record<string, string>
      name: string
      template: boolean
    }
  }
}
