// TypesFromSerializers CacheKey 0871304223f9d0cb621db13b6d3e07b4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsFormData {
      id?: string
      data: Record<string, string>
      name: string
      template: boolean
    }
  }
}
