// TypesFromSerializers CacheKey 96a5dccd2c05be3c9c94c654161fe536
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsFormData {
      id?: unknown
      data: unknown
      element: unknown
      name: unknown
    }
  }
}
