// TypesFromSerializers CacheKey ed67e905f23f27ae88f8332ab1064580
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsIndex {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      template: boolean
      updated_at: string | Date
    }
  }
}
