// TypesFromSerializers CacheKey 196c706acacb76d12817b8adb22dc366
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsIndex {
      id: string
      data: Record<string, string>
      name: string
      slug: string
      template: boolean
    }
  }
}
