// TypesFromSerializers CacheKey fffe8dea2aa86e287038131fdeac761c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsPersisted {
      id: string
      data: Record<string, string>
      name: string
      slug: string
      template: boolean
    }
  }
}
