// TypesFromSerializers CacheKey 54395074080d65dab18c1662ba2286c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsPersisted {
      id: unknown
      created_at: unknown
      data: unknown
      element: unknown
      name: unknown
      updated_at: unknown
    }
  }
}
