// TypesFromSerializers CacheKey 1498404fe02dda4aab9356c2a594c8a1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElementsShow {
      id: unknown
      created_at: unknown
      data: unknown
      element: unknown
      name: unknown
      updated_at: unknown
    }
  }
}
