// TypesFromSerializers CacheKey d262ce3fefe63592eb685c7437376289
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SmtpsIndex {
      id: string
      address?: string
      domain?: string
      host: string
      name: string
      notes?: string
      password?: string
      port?: number
      security: "plain" | "tls" | "ssl"
      username?: string
    }
  }
}
