// TypesFromSerializers CacheKey 0ab1e8d5bb0d67cb7bbf26356f00ccd7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IntegrationsEdit {
      id: string
      active: boolean
      credential_fields: Record<string, string[]>
      credentials: Record<string, string>
      medium: string
      name: string
      presets: Record<string, {
    medium: string
    auth_profile: string
    fields: Array<{
      key: string
      secret: boolean
    }>
  }>
      provider: string
      providers: string[]
      providers_by_medium: Record<string, string[]>
    }
  }
}
