// TypesFromSerializers CacheKey 4a60190051b725aef0eef872e2e57a0f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IntegrationsFormData {
      id?: string
      active: boolean
      credential_fields: Record<string, string[]>
      credentials: Record<string, string>
      medium: string
      name: string
      presets: Record<string, {
    medium: string
    auth_profile: string
    fields: Array<{
      key: string
      secret: boolean
    }>
  }>
      provider: string
      providers: string[]
      providers_by_medium: Record<string, string[]>
    }
  }
}
