// TypesFromSerializers CacheKey 28a14e073cc643b317bb5765e0002e17
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IntegrationsIndex {
      id: string
      active: boolean
      credentials: object
      medium: string
      name: string
      provider: string
    }
  }
}
