// TypesFromSerializers CacheKey fb20d7b82aba05c225163aeb607b972b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IntegrationsPersisted {
      id: string
      active: boolean
      credentials: object
      medium: string
      name: string
      provider: string
    }
  }
}
