// TypesFromSerializers CacheKey aeb363abf1f3145e49c473f7f13c3b61
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'
import type Slide from '../Slide'

declare global {
  namespace Schema {
    interface TemplatesEdit {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slides: Slide[]
      slug: string
      updated_at: string | Date
    }
  }
}
