// TypesFromSerializers CacheKey d0de65af99313c63d29a8b55c7d44e1c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'
import type SlidesEdit from '../Slides/Edit'

declare global {
  namespace Schema {
    interface TemplatesEdit {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slides: SlidesEdit[]
      slug: string
      updated_at: string | Date
    }
  }
}
