// TypesFromSerializers CacheKey c19f34d40979d6efe2c70442a0984f4f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'
import type SlidesEdit from '../Slides/Edit'

declare global {
  namespace Schema {
    interface TemplatesEdit {
      id: string
      circle: CirclesPersisted
      name?: string
      settings: Record<string, string>
      slides: SlidesEdit[]
      slug: string
    }
  }
}
