// TypesFromSerializers CacheKey 816b13f850f0b94d04400956d913f821
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlidesFormData from '../Slides/FormData'

declare global {
  namespace Schema {
    interface TemplatesFormData {
      id?: string
      slug?: string
      name?: string
      settings: Record<string, string>
      slides: SlidesFormData[]
    }
  }
}
