// TypesFromSerializers CacheKey 8a601d0068d7f69469136a05ebdb5125
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TemplatesFormData {
      id?: string
      slug?: string
      name?: string
      settings: Record<string, string>
      slides: Record<string, string>
    }
  }
}
