// TypesFromSerializers CacheKey f7ea86329820873c46a22dcdd91e6d43
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface TemplatesIndex {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slug: string
      updated_at: string | Date
    }
  }
}
