// TypesFromSerializers CacheKey a4f71ce261c7e987605deb4b8770632f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Slide from '../../Slide'
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface TemplatesIndex {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slides: Slide[]
      slug: string
      updated_at: string | Date
    }
  }
}
