// TypesFromSerializers CacheKey 9a48195dfba7029e9875a9aca16386b8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface TemplatesIndex {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slides: Record<string, string>
      slug: string
      updated_at: string | Date
    }
  }
}
