// TypesFromSerializers CacheKey 5a2a98bae53f3a9c872a6c198f4e0bec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Slide from '../../Slide'
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface TemplatesPersisted {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slides: Slide[]
      slug: string
      updated_at: string | Date
    }
  }
}
