// TypesFromSerializers CacheKey bc5a362b29a6075d959bbf694f960973
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface TemplatesPersisted {
      id: string
      circle: CirclesPersisted
      name?: string
      settings: Record<string, string>
      slug: string
    }
  }
}
