// TypesFromSerializers CacheKey 51fdb74e98d1d12dc7bbf060b37a636e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface TemplatesPersisted {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slug: string
      updated_at: string | Date
    }
  }
}
