// TypesFromSerializers CacheKey 0cb691a9f0b9d2ff2989213514f9a52f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Slide from '../../Slide'
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface TemplatesShow {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slides: Slide[]
      slug: string
      updated_at: string | Date
    }
  }
}
