// TypesFromSerializers CacheKey 1763c77b5bbfe223a46d4e4b6a0d58f4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface TemplatesShow {
      id: string
      circle: CirclesPersisted
      created_at: string | Date
      name?: string
      settings: Record<string, string>
      slides: Record<string, string>
      slug: string
      updated_at: string | Date
    }
  }
}
