// TypesFromSerializers CacheKey ea6319f4d9631cd64d251f6c81735eac
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'
import type SlidesShow from '../Slides/Show'

declare global {
  namespace Schema {
    interface TemplatesShow {
      id: string
      circle: CirclesPersisted
      name?: string
      settings: Record<string, string>
      slides: SlidesShow[]
      slug: string
    }
  }
}
