// TypesFromSerializers CacheKey 8a836bd1963e6b7f0d45021ab7ef58de
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesEdit {
      id: unknown
      content: unknown
      created_at: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
