// TypesFromSerializers CacheKey e79a6ebfc2a37f393432bdb998cf1e27
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesIndex {
      id: unknown
      content: unknown
      created_at: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
