// TypesFromSerializers CacheKey a972cbb9cbc2ba338beffac2f5307a11
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesPersisted {
      id: string
      content?: string
      created_at: string | Date
      name?: string
      order?: number
      presentation_id?: string
      presentation_template_id?: string
      slug: string
      updated_at: string | Date
    }
  }
}
