// TypesFromSerializers CacheKey 65dcfcd6c30729df2a70aa75e1814098
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesPersisted {
      id: unknown
      content: unknown
      created_at: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
