// TypesFromSerializers CacheKey 28c9389114845d1e889ccc8c1c664363
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesShow {
      id: unknown
      content: unknown
      created_at: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
