// TypesFromSerializers CacheKey 0fc970ac6f2b6c157782bcb42ac0804c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesEdit {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      order?: number
      template: boolean
      updated_at: string | Date
    }
  }
}
