// TypesFromSerializers CacheKey 060eb7c95875fd2bb3878a17569fea46
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesFormData {
      id?: unknown
      slug?: unknown
      content: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
    }
  }
}
