// TypesFromSerializers CacheKey 7e4f99b4ada8c1e2ca84865847c4eaf3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesFormData {
      id?: string
      data: Record<string, string>
      name: string
      order?: number
      template: boolean
    }
  }
}
