// TypesFromSerializers CacheKey f4a8aa0e16cb103b17868f450bed9fa7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesIndex {
      id: unknown
      slug?: unknown
      content: unknown
      created_at: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
      updated_at: unknown
    }
  }
}
