// TypesFromSerializers CacheKey 2f5d3a13e76f8f021228d8e9dbbddc0a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesIndex {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      order?: number
      template: boolean
      updated_at: string | Date
    }
  }
}
