// TypesFromSerializers CacheKey cda0fcfac630d9485e95f334660a0332
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesPersisted {
      id: unknown
      slug?: unknown
      content: unknown
      created_at: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
      updated_at: unknown
    }
  }
}
