// TypesFromSerializers CacheKey f050c5291d9f1947edd4c9e9f92e3569
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesPersisted {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      order?: number
      template: boolean
      updated_at: string | Date
    }
  }
}
