// TypesFromSerializers CacheKey 85689ea3363faee62061874772f42aae
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PresentationsPersisted from '../../Presentations/Persisted'

declare global {
  namespace Schema {
    interface PresentationSlidesShow {
      id: string
      created_at: string | Date
      data: Record<string, string>
      name: string
      order?: number
      presentations: PresentationsPersisted[]
      template: boolean
      updated_at: string | Date
    }
  }
}
