// TypesFromSerializers CacheKey 2700de71dbfd6b8fc3c3a2d6e2b9633b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlidesShow {
      id: unknown
      slug?: unknown
      content: unknown
      created_at: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
      updated_at: unknown
    }
  }
}
