// TypesFromSerializers CacheKey d03aac2975b6bc0414e40bcd36af21cb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface GroupsEdit {
      id: string
      circle_id: string
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
