// TypesFromSerializers CacheKey ee57e5f72551263f1386caacc54a4e8f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface GroupsFormData {
      id?: string
      slug?: string
      circle_id: string
      name: string
    }
  }
}
