// TypesFromSerializers CacheKey 493b3d496aff543a79aec8f8f704b01f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface GroupsFormData {
      id?: number
      slug?: string
      circle_id: number
      name: string
    }
  }
}
