// TypesFromSerializers CacheKey 10a3b0cc070e95c8d4e8e8402fd760ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface GroupsIndex {
      id: string
      circle_id: string
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
