# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DecentExposure::Generators::ScaffoldTemplatesGenerator`.
# Please instead update this file by running `bin/tapioca dsl DecentExposure::Generators::ScaffoldTemplatesGenerator`.

class DecentExposure::Generators::ScaffoldTemplatesGenerator
  sig { returns(::String) }
  def template_engine; end
end
