// TypesFromSerializers CacheKey f10fbd23611401356b9cf4ae7690daa3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface UsersEdit {
      id: number
      active: boolean
      confirmation_sent_at?: string | Date
      confirmation_token?: string
      confirmed_at?: string | Date
      current_sign_in_at?: string | Date
      current_sign_in_ip?: string
      email: string
      encrypted_password: string
      failed_attempts: number
      last_sign_in_at?: string | Date
      last_sign_in_ip?: string
      locked_at?: string | Date
      remember_created_at?: string | Date
      reset_password_sent_at?: string | Date
      reset_password_token?: string
      sign_in_count: number
      table_preferences: Record<string, string>
      unconfirmed_email?: string
      unlock_token?: string
      user_preferences: Record<string, string>
    }
  }
}
