// TypesFromSerializers CacheKey fb9a4b9c8a97bb050701c0fe80ba95d8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersEdit {
      id: string
      active: boolean
      circles: CirclesPersisted[]
      created_at: string | Date
      email: string
      person: Person
      person_id?: string
      roles: Role[]
      updated_at: string | Date
    }
  }
}
