// TypesFromSerializers CacheKey d5d8a3253a8b460865300855ebafb26a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface UsersFormData {
      id?: string
      active: boolean
      circles: CirclesPersisted[]
      email: string
      person_id?: string
    }
  }
}
