// TypesFromSerializers CacheKey c39c421a3477d16119da02fe7c559c23
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type UserTablePreferences from '../../UserTablePreferences'
import type UserPreferences from '../../UserPreferences'
import type CirclesPersisted from '../Circles/Persisted'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersIndex {
      id: string
      active: boolean
      circles: CirclesPersisted[]
      created_at: string | Date
      email: string
      person: Person
      person_id?: string
      roles: Role[]
      slug: string
      table_preferences: UserTablePreferences
      updated_at: string | Date
      user_preferences: UserPreferences
    }
  }
}
