// TypesFromSerializers CacheKey cea38bad3d31ebf0c88ec718ebb50795
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IUserTablePreferences from '../../IUserTablePreferences'
import type IUserPreferences from '../../IUserPreferences'
import type CirclesPersisted from '../Circles/Persisted'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersInertiaShare {
      id?: string
      active: boolean
      circles: CirclesPersisted[]
      email: string
      person: Person
      person_id?: string
      roles: Role[]
      table_preferences: IUserTablePreferences
      user_preferences: IUserPreferences
    }
  }
}
