// TypesFromSerializers CacheKey 10bb1da9ecb410ada75edccaef09b2cc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface UsersPersisted {
      id: string
      active: boolean
      email: string
      person_id?: string
      slug: string
    }
  }
}
