// TypesFromSerializers CacheKey a8cca57428aa1db00527aeb9087389ca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesShare from '../Circles/Share'

declare global {
  namespace Schema {
    interface UsersShare {
      id: number
      circles: CirclesShare[]
      created_at: string | Date
      email: string
      updated_at: string | Date
    }
  }
}
