// TypesFromSerializers CacheKey 597cd2aa01c5cc3a697695f5baada9e3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Circle } from '../Circle'

declare global {
  namespace Schema {
    interface UsersShare {
      id: number
      circles: Circle[]
      createdAt: string | Date
      email: string
      updatedAt: string | Date
    }
  }
}
