// TypesFromSerializers CacheKey 6ae58a382b8cff4385e5c92e66018962
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesShare from '../Circles/Share'

declare global {
  namespace Schema {
    interface UsersShare {
      id: number
      active_circle: CirclesShare
      active_circle_id?: number
      circles: CirclesShare[]
      created_at: string | Date
      email: string
      updated_at: string | Date
    }
  }
}
