// TypesFromSerializers CacheKey babd7ed2448a7d3140a43db6210e57cb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IUserTablePreferences from '../../IUserTablePreferences'
import type IUserPreferences from '../../IUserPreferences'
import type CirclesPersisted from '../Circles/Persisted'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersShow {
      id: string
      active: boolean
      circles: CirclesPersisted[]
      created_at: string | Date
      email: string
      person: Person
      person_id?: string
      roles: Role[]
      table_preferences: IUserTablePreferences
      updated_at: string | Date
      user_preferences: IUserPreferences
    }
  }
}
