// TypesFromSerializers CacheKey 183d9b81081b291e1c3a8b1c4ae27477
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type MembershipsPersisted from '../../Memberships/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteractionResponsesIndex {
      id: string
      membership: MembershipsPersisted
      membership_id: string
      presentation_interaction_id: string
      response_data: Record<string, string>
    }
  }
}
