// TypesFromSerializers CacheKey c11f86543d3bca910336649175b27c7a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationInteractionResponsesPersisted {
      id: string
      membership_id: string
      presentation_interaction_id: string
      response_data: Record<string, string>
    }
  }
}
