// TypesFromSerializers CacheKey 342ca91b2269c1ba8cdf4278e9462fb7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type MembershipsPersisted from '../../Memberships/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteractionResponsesShow {
      id: string
      membership: MembershipsPersisted
      membership_id: string
      presentation_interaction_id: string
      response_data: Record<string, string>
    }
  }
}
