// TypesFromSerializers CacheKey 6f0ab4691966fe96cf5d9f957d4ae17b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsEdit {
      id: string
      active: boolean
      created_at: string | Date
      name?: string
      theme_id: string
      updated_at: string | Date
    }
  }
}
