// TypesFromSerializers CacheKey 1a587ae3f5ac3ab320f3ba0694ca3a8b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlidesEdit from '../Slides/Edit'

declare global {
  namespace Schema {
    interface PresentationsEdit {
      id: string
      active: boolean
      created_at: string | Date
      name: string
      slides: SlidesEdit[]
      slug: string
      theme_id: string
      updated_at: string | Date
    }
  }
}
