// TypesFromSerializers CacheKey a2f991665f2deea0035d40a7e5a1d663
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Theme from '../Theme'

declare global {
  namespace Schema {
    interface PresentationsEdit {
      id: number
      name?: string
      theme: Theme
      theme_id: number
    }
  }
}
