// TypesFromSerializers CacheKey 97af5d3db8d4b0d69b89ff75f38d9001
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PresentationSlidesPersisted from '../PresentationSlides/Persisted'

declare global {
  namespace Schema {
    interface PresentationsFormData {
      id?: string
      active: boolean
      name: string
      slides: PresentationSlidesPersisted[]
      theme_id: string
    }
  }
}
