// TypesFromSerializers CacheKey c115370b4d80f89cf5887504415820ac
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Slide from '../../Slide'

declare global {
  namespace Schema {
    interface PresentationsFormData {
      id?: string
      active: boolean
      name: string
      slides: Slide
      theme_id: string
    }
  }
}
