// TypesFromSerializers CacheKey e504b4c023da5e223532a63f2a57dd3b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Theme from '../Theme'

declare global {
  namespace Schema {
    interface PresentationsFormData {
      id?: number
      name?: string
      theme: Theme
      theme_id: number
    }
  }
}
