// TypesFromSerializers CacheKey 60fa840a7e2d23e6da5845e01d57ea0d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ThemesShow from '../Themes/Show'

declare global {
  namespace Schema {
    interface PresentationsIndex {
      id: string
      active: boolean
      created_at: string | Date
      name?: string
      slug: string
      theme: ThemesShow
      theme_id: string
      updated_at: string | Date
    }
  }
}
