// TypesFromSerializers CacheKey f9f85484bf8f9875ac640d8cd690d959
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ThemesShow from '../Themes/Show'

declare global {
  namespace Schema {
    interface PresentationsIndex {
      id: string
      created_at: string | Date
      name?: string
      theme: ThemesShow
      theme_id: string
      updated_at: string | Date
    }
  }
}
