// TypesFromSerializers CacheKey 3fb36e2ae68fb1f12549c256178b518b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Theme from '../Theme'

declare global {
  namespace Schema {
    interface PresentationsIndex {
      id: number
      created_at: string | Date
      name?: string
      theme: Theme
      theme_id: number
      updated_at: string | Date
    }
  }
}
