// TypesFromSerializers CacheKey ffead876c3f3078caf3bb4a4a508b5f4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PresentationsSettings from './Settings'

declare global {
  namespace Schema {
    interface PresentationsInertiaShare {
      id: string
      active: boolean
      name: string
      settings: PresentationsSettings
      slug: string
      theme_id: string
    }
  }
}
