// TypesFromSerializers CacheKey d04f09c0ef06614d79e108c413efd21a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsInertiaShare {
      id: string
      active: boolean
      name: string
      slug: string
      theme_id: string
    }
  }
}
