// TypesFromSerializers CacheKey a6ea124f01648f837e065eb59cbc3d73
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsInertiaShare {
      id: string
      name?: string
      slug: string
    }
  }
}
