// TypesFromSerializers CacheKey 04228f2ef9f15f5791176c11995471f1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsPersisted {
      id: string
      active: boolean
      created_at: string | Date
      name: string
      slides: Record<string, string>
      slug: string
      theme_id: string
      updated_at: string | Date
    }
  }
}
