// TypesFromSerializers CacheKey c2c3a2ec54945f7ab1aa33bbda81e63d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsPersisted {
      id: string
      active: boolean
      created_at: string | Date
      name: string
      slug: string
      theme_id: string
      updated_at: string | Date
    }
  }
}
