// TypesFromSerializers CacheKey eee785456c252ba4f1fc78e6c9e37074
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PresentationsSettings from './Settings'

declare global {
  namespace Schema {
    interface PresentationsPersisted {
      id: string
      active: boolean
      name: string
      settings: PresentationsSettings
      slug: string
      theme_id: string
    }
  }
}
