// TypesFromSerializers CacheKey 42b61704c055cfb8fb03b06ef0b68223
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsPresentation {
      id: number
      created_at: string | Date
      name?: string
      theme_id: number
      updated_at: string | Date
    }
  }
}
