// TypesFromSerializers CacheKey 225b9c6c38dc677641ec8b9c2649c698
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlidesPresentation from '../Slides/Presentation'

declare global {
  namespace Schema {
    interface PresentationsPresentation {
      id: string
      active: boolean
      active_slide_id?: string
      name: string
      slides: SlidesPresentation[]
      slug: string
      theme_id: string
    }
  }
}
