// TypesFromSerializers CacheKey 5bb57b26fc8efc2ac341e899742cf95d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PresentationsOrgsPersisted from './Orgs/Persisted'
import type SlidesPresentation from '../Slides/Presentation'

declare global {
  namespace Schema {
    interface PresentationsPresentation {
      id: string
      active: boolean
      active_slide_id?: string
      name: string
      orgs: PresentationsOrgsPersisted[]
      slides: SlidesPresentation[]
      slug: string
      theme_id: string
    }
  }
}
