// TypesFromSerializers CacheKey 8c2b7ef11de51e8e2b8734f9af0dbd94
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsShallow {
      id: string
      created_at: string | Date
      name?: string
      theme_id: string
      updated_at: string | Date
    }
  }
}
