// TypesFromSerializers CacheKey bec573bd47c2cb4bc0610576a6c78d22
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SlidesShow from '../Slides/Show'
import type TemplatesPersisted from '../Templates/Persisted'

declare global {
  namespace Schema {
    interface PresentationsShow {
      id: string
      active: boolean
      name: string
      slides: SlidesShow[]
      slides_count: number
      slug: string
      template?: TemplatesPersisted
      template_id: string
      theme_id: string
    }
  }
}
