// TypesFromSerializers CacheKey a12961a915544f0d545495c637363b9c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ElementControlsPayload from '../../ElementControlsPayload'
import type SlidesShow from '../Slides/Show'
import type TemplatesPersisted from '../Templates/Persisted'

declare global {
  namespace Schema {
    interface PresentationsShow {
      id: string
      active: boolean
      element_controls: ElementControlsPayload
      name: string
      slides: SlidesShow[]
      slides_count: number
      slug: string
      template?: TemplatesPersisted
      template_id: string
      theme_id: string
    }
  }
}
