// TypesFromSerializers CacheKey 1764aee1bf08ae4cf740a1c792b08c68
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ElementControlsPayload from '../../ElementControlsPayload'
import type PresentationsSettings from './Settings'
import type SlidesShow from '../Slides/Show'
import type TemplatesPersisted from '../Templates/Persisted'

declare global {
  namespace Schema {
    interface PresentationsShow {
      id: string
      active: boolean
      element_controls: ElementControlsPayload
      name: string
      settings: PresentationsSettings
      slides: SlidesShow[]
      slides_count: number
      slug: string
      template?: TemplatesPersisted
      template_id: string
      theme_id: string
    }
  }
}
