// TypesFromSerializers CacheKey 5db9c4930e3a0373934f565b2b2757a0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsEdit {
      id: string
      circle_id: string
      created_at: string | Date
      description?: string
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
