// TypesFromSerializers CacheKey e3c3ea355ee3e91ecb86e42a59ae898b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsEdit {
      id: string
      created_at: string | Date
      description?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
