// TypesFromSerializers CacheKey f47bd1432368abca25935b3748f949b8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsEdit {
      id: number
      description?: string
      name?: string
      slug?: string
    }
  }
}
