// TypesFromSerializers CacheKey 145fb84b43a30bba01863812a3e96add
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsFormData {
      id?: string
      slug?: string
      description?: string
      name: string
    }
  }
}
