// TypesFromSerializers CacheKey c6a6273ca303f2c44bec83850e4b77cd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsFormData {
      id?: string
      slug?: string
      description?: string
      name?: string
    }
  }
}
