// TypesFromSerializers CacheKey cc03610531f2b9ddb10a0e18fc93ed58
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsFormData {
      id?: string
      description?: string
      name?: string
      slug: string
    }
  }
}
