// TypesFromSerializers CacheKey c34fcb5c839e0924f3f910a18d56f194
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsIndex {
      id: string
      created_at: string | Date
      description?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
