// TypesFromSerializers CacheKey a52d851552a870acf094749cd89a9b55
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsIndex {
      id: string
      created_at: string | Date
      description?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
