// TypesFromSerializers CacheKey f33d99d37d62a5ec51152dfed95bf5e9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsIndex {
      id: string
      created_at: string | Date
      description?: string
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
