// TypesFromSerializers CacheKey 50be5fc0a9cfb3a9fd7daa24d80650a4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsPersisted {
      id: string
      created_at: string | Date
      description?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
