// TypesFromSerializers CacheKey 074297ec11047204d58330507a2653ac
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsPersisted {
      id: string
      created_at: string | Date
      description?: string
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
