// TypesFromSerializers CacheKey 4afca93a6d2a542816aaf0c23e3ee3b8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsShallow {
      id: string
      created_at: string | Date
      description?: string
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
