// TypesFromSerializers CacheKey 6965e687c0103a6de6bb44cbdce813d2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsShow {
      id: number
      created_at: string | Date
      description?: string
      name?: string
      slug?: string
      updated_at: string | Date
    }
  }
}
