// TypesFromSerializers CacheKey 293eeecf1d2bfc075945c9ef563cb051
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesOptions from '../Circles/Options'

declare global {
  namespace Schema {
    interface OrgsShow {
      id: string
      circle: CirclesOptions
      circle_id: string
      created_at: string | Date
      description?: string
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
