// TypesFromSerializers CacheKey a379277088aca25891a7037b66691173
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface OrgsShow {
      id: string
      circle: CirclesPersisted
      description?: string
      name: string
      slug: string
    }
  }
}
