// TypesFromSerializers CacheKey a5b9413fa3bd96f68389710393249256
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesEdit {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
