// TypesFromSerializers CacheKey 25b7f4f1e2f4ca28c5fd599e71905ae7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesFormData {
      id?: unknown
    }
  }
}
