// TypesFromSerializers CacheKey c03350737fd6df9a7504da89f119c4e2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesIndex {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
