// TypesFromSerializers CacheKey 1016f61dd894b795db7432cb02b34ff6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesPersisted {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
