// TypesFromSerializers CacheKey d019edeeb684cc8197f9a4855347d517
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesPersisted {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
