// TypesFromSerializers CacheKey f49d60c2394d282177a2fc7c741ba4a2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesShow {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
