// TypesFromSerializers CacheKey 19d619ee6c2750bd4ae9d13a6ad5ede5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationVotesShow {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
