// TypesFromSerializers CacheKey f998721a90e7c231d1e495deb3c27860
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../../Money'

declare global {
  namespace Schema {
    interface PresentationsOrgsPersisted {
      id: string
      ask: Money
      description?: string
      name: string
      slug: string
    }
  }
}
