// TypesFromSerializers CacheKey ae59c675918154f579a0f0490eb845bc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesBasic {
      id: string
      categorizable_type: string
      created_at: string | Date
      description?: string
      name: string
      plural: string
      qty: number
      slug: string
      updated_at: string | Date
    }
  }
}
