// TypesFromSerializers CacheKey d20f4f5ae5a2a082d2defccf48b825fc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesEdit {
      id: string
      categorizable_type: string
      description?: string
      name: string
      slug: string
    }
  }
}
