// TypesFromSerializers CacheKey d8887f1aa99924892fee3561ef63d4c5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesIndex {
      id: string
      categorizable_type: string
      created_at: string | Date
      description?: string
      name: string
      plural: string
      qty: number
      slug: string
      updated_at: string | Date
    }
  }
}
