// TypesFromSerializers CacheKey ddc68bdccbd2f8cd0bfee11306c47f16
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesOptions {
      id: string
      category_with_type: string
      name: string
      slug: string
    }
  }
}
