// TypesFromSerializers CacheKey 9217327d6493dddac98fb3bd3c161484
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesPersisted {
      id: string
      categorizable_type: string
      description?: string
      name: string
      slug: string
    }
  }
}
