// TypesFromSerializers CacheKey 772f3ccf3518e74078e2808a9fbe8a97
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'

declare global {
  namespace Schema {
    interface MembershipsEdit {
      id: string
      active: boolean
      funds: Money
      name: string
      number?: string
      slug: string
    }
  }
}
