// TypesFromSerializers CacheKey 2a92f45045dd18c6055e90123e1d6858
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'

declare global {
  namespace Schema {
    interface MembershipsEdit {
      id: string
      active: boolean
      created_at: string | Date
      funds: Money
      name: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
