// TypesFromSerializers CacheKey 910a35d591e6a45b29229c0de751665f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'

declare global {
  namespace Schema {
    interface MembershipsFormData {
      id?: string
      slug?: string
      active: boolean
      funds: Money
      name: string
      number?: string
    }
  }
}
