// TypesFromSerializers CacheKey 68e6d33f9badc2264fbae96fbdbcf9e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembershipsIndex {
      id: string
      created_at: string | Date
      updated_at: string | Date
    }
  }
}
