// TypesFromSerializers CacheKey f6c73e684c7e4cffc0356c5d3a62029f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'

declare global {
  namespace Schema {
    interface MembershipsPersisted {
      id: string
      active: boolean
      funds: Money
      name: string
      number?: string
      slug: string
    }
  }
}
