// TypesFromSerializers CacheKey c15715460f30d1a68b28d326425978da
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembershipsPersisted {
      id: string
      created_at: string | Date
      updated_at: string | Date
    }
  }
}
