// TypesFromSerializers CacheKey fd889f430dafe0aaf148296a9956011e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'

declare global {
  namespace Schema {
    interface MembershipsPersisted {
      id: string
      active: boolean
      created_at: string | Date
      funds: Money
      name: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
