// TypesFromSerializers CacheKey ef580224b80c297fc69329a8af1e572d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface MembershipsShow {
      id: string
      active: boolean
      circle: CirclesPersisted
      funds: Money
      name: string
      number?: string
      slug: string
    }
  }
}
