// TypesFromSerializers CacheKey ef52778198e55f7edd4dbda12aa3a629
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface MembershipsShow {
      id: string
      active: boolean
      circle: CirclesPersisted
      created_at: string | Date
      funds: Money
      name: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
