// TypesFromSerializers CacheKey 5351742863f0b49528bb8cef6037f291
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembershipsShow {
      id: string
      created_at: string | Date
      updated_at: string | Date
    }
  }
}
