// TypesFromSerializers CacheKey 41f74c43253a81492591b484605a9573
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleEdit {
      id: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      slug: string
      user: User
    }
  }
}
