// TypesFromSerializers CacheKey b625170e0e007b7fa6c42382f382967f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleFormData {
      id?: string
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
    }
  }
}
