// TypesFromSerializers CacheKey 37fd45d0b4b15bd6c6363b1de0222310
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleIndex {
      id: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      slug: string
    }
  }
}
