// TypesFromSerializers CacheKey d9dbf7daa17fc14ce19f4f4211774c5c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleIndex {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      updated_at: string | Date
    }
  }
}
