// TypesFromSerializers CacheKey 6c3a6912c79b8a2a103bfb2e7646e54d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeoplePersisted {
      id: string
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
