// TypesFromSerializers CacheKey 8d522c9509262f003924955a00f91960
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleShow {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      updated_at: string | Date
      user: User
    }
  }
}
