// TypesFromSerializers CacheKey cca3db80ef874740606569101c9fde55
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleShow {
      id: string
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: unknown
      slug: string
      updated_at: string | Date
      user: User
    }
  }
}
