// TypesFromSerializers CacheKey ceb7c644f01e82905ec287ad4a3bc846
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleShow {
      id: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      slug: string
      user: User
    }
  }
}
