// TypesFromSerializers CacheKey 2220aae316d13fbd29c4831db218d411
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistribution {
      id?: string
      name: string
      template: boolean
      type?: number
    }
  }
}
