// TypesFromSerializers CacheKey 2fdc79ba5dd8d616e1bb5260b58086b5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationDistribution {
      id?: string
      name: string
      template: boolean
      type?: number
    }
  }
}
