// TypesFromSerializers CacheKey 1c32006255eaa193f5b661c5e2d73261
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElement {
      id?: string
      data: Record<string, string>
      name: string
      template: boolean
    }
  }
}
