// TypesFromSerializers CacheKey 4731989f720e013298d1d079cc52ab22
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElement {
      id?: unknown
      data: unknown
      element: unknown
      name: unknown
    }
  }
}
