// TypesFromSerializers CacheKey a4770844082bdbd9972a7f83729c6fa5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationElement {
      id?: string
      data: Record<string, string>
      name: string
      template: boolean
    }
  }
}
