// TypesFromSerializers CacheKey 897a18ea09825efeec77a3ada6335d28
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteraction {
      id?: string
      accepting_responses: boolean
      config: Record<string, string>
      interaction_ui_template: InteractionUiTemplatesPersisted
      member_ui: Record<string, string>
      name: string
      results: Record<string, string>
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
