// TypesFromSerializers CacheKey bd5ef9a16f9a423fe0abd87cfb6ec122
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationInteraction {
      id?: string
      accepting_responses: boolean
      config: Record<string, string>
      name: string
      results: Record<string, string>
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
