// TypesFromSerializers CacheKey 9cc12416de0e13bcbe43856abc4d14d9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface PresentationInteraction {
      id?: string
      accepting_responses: boolean
      config: Record<string, string>
      interaction_ui_template: InteractionUiTemplatesPersisted
      name: string
      results: Record<string, string>
      trigger_conditions: Record<string, string>
      trigger_type: "manual" | "slide"
    }
  }
}
