// TypesFromSerializers CacheKey b973ee09c80acb6cc55227b3a47a25ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationMessage {
      id?: string
      slug?: string
      body: string
      delivery_results: Record<string, {
    recipient?: string | null
    status?: string
    code?: string
    error_message?: string
    skip_reason?: string
    provider_message_id?: string
  }>
      integration_id?: string
      medium: string
      message_template_id?: string
      name: string
      skip_interaction_id?: string
      status: string
      subject?: string
    }
  }
}
