// TypesFromSerializers CacheKey 383544195200b8bb3693ad20a63590ef
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationSlide {
      id?: unknown
      slug?: unknown
      content: unknown
      name: unknown
      order: unknown
      presentation_id: unknown
      presentation_template_id: unknown
    }
  }
}
