// TypesFromSerializers CacheKey b9a79ddd0ca74d044a7f5c77a1c17cb1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface InteractionConfigTemplatesEdit {
      id?: string
      slug?: string
      config: Record<string, string>
      field_types: string[]
      metrics: string[]
      name: string
      reducers: string[]
    }
  }
}
