// TypesFromSerializers CacheKey 0f6faf50df6f88e1516a9b6aabd0d8f6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface InteractionConfigTemplatesEdit {
      id?: string
      slug?: string
      config: Record<string, string>
      field_types: string[]
      interaction_ui_template?: InteractionUiTemplatesPersisted
      metrics: string[]
      name: string
      reducers: string[]
    }
  }
}
