// TypesFromSerializers CacheKey 043b2783ca456e7c0d602d1b21878ff3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface InteractionConfigTemplatesEdit {
      id?: string
      slug?: string
      config: Record<string, string>
      field_types: string[]
      interaction_ui_template?: InteractionUiTemplatesPersisted
      interaction_ui_templates: InteractionUiTemplatesPersisted[]
      metrics: string[]
      name: string
      reducers: string[]
    }
  }
}
