// TypesFromSerializers CacheKey d4f1a5b6b22566ae53c39cce0e6f1e30
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface InteractionConfigTemplatesFormData {
      id?: string
      slug?: string
      config: Record<string, string>
      field_types: string[]
      metrics: string[]
      name: string
      reducers: string[]
    }
  }
}
