// TypesFromSerializers CacheKey 30b2fecd8b16d8cc9ec188b16cb35989
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface InteractionConfigTemplatesFormData {
      id?: string
      slug?: string
      config: Record<string, string>
      field_types: string[]
      interaction_ui_template?: InteractionUiTemplatesPersisted
      interaction_ui_templates: InteractionUiTemplatesPersisted[]
      member_ui: Record<string, string>
      metrics: string[]
      name: string
      reducers: string[]
    }
  }
}
