// TypesFromSerializers CacheKey 532ac0b8a95ccace873799b023dddcfe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CirclesPersisted from '../Circles/Persisted'

declare global {
  namespace Schema {
    interface InteractionConfigTemplatesIndex {
      id: string
      circle: CirclesPersisted
      config: Record<string, string>
      name: string
      slug: string
    }
  }
}
