// TypesFromSerializers CacheKey 0ec723b7f08466b019696f779f458795
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InteractionUiTemplatesPersisted from '../InteractionUiTemplates/Persisted'

declare global {
  namespace Schema {
    interface InteractionConfigTemplatesPersisted {
      id: string
      config: Record<string, string>
      interaction_ui_template?: InteractionUiTemplatesPersisted
      member_ui: Record<string, string>
      name: string
      slug: string
    }
  }
}
