// TypesFromSerializers CacheKey 45a428e8c975aa81a26abe5a72d3e0d5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsEdit {
      id: string
      contactable_id: string
      contactable_type: string
      created_at: string | Date
      notes: unknown
      primary_address_id: unknown
      primary_email_id: unknown
      primary_phone_id: unknown
      updated_at: string | Date
    }
  }
}
