// TypesFromSerializers CacheKey cc513d766cee75d05a5b18009807ea5c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsFormData {
      id?: string
      contactable_id: string
      contactable_type: string
      notes: unknown
      primary_address_id: unknown
      primary_email_id: unknown
      primary_phone_id: unknown
    }
  }
}
