// TypesFromSerializers CacheKey 8a4c6316746263bc4fb99777a107c6cb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsIndex {
      id: string
      contactable_id: string
      contactable_type: string
      created_at: string | Date
      notes: unknown
      primary_address_id: unknown
      primary_email_id: unknown
      primary_phone_id: unknown
      updated_at: string | Date
    }
  }
}
