// TypesFromSerializers CacheKey 54105454ae0db5a7c957a3677668a782
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Address from '../Address'
import type Email from '../Email'
import type Phone from '../Phone'

declare global {
  namespace Schema {
    interface ContactsPersisted {
      id: string
      addresses: Address[]
      contactable_id: string
      contactable_type: string
      created_at: string | Date
      emails: Email[]
      notes: unknown
      phones: Phone[]
      primary_address_id: unknown
      primary_email_id: unknown
      primary_phone_id: unknown
      updated_at: string | Date
    }
  }
}
